#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 14, 2025 09:18:17 PM -03  platform: Windows NT
import sys_estoque_support
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
import sys_estoque_support

_location = os.path.dirname(__file__)


_bgcolor = '#efebe7'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: sys_estoque_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'clearlooks.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('clearlooks')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("778x516+405+168")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#efebe7")
        top.configure(highlightbackground="#efebe7")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame_de_Busca = tk.LabelFrame(self.top)
        self.Frame_de_Busca.place(relx=0.039, rely=0.64, relheight=0.169, relwidth=0.933)
        self.Frame_de_Busca.configure(relief='groove')
        self.Frame_de_Busca.configure(foreground="black")
        self.Frame_de_Busca.configure(text='''Buscar de Produtos''')
        self.Frame_de_Busca.configure(background="#efebe7")
        self.Frame_de_Busca.configure(highlightbackground="#efebe7")
        self.Frame_de_Busca.configure(highlightcolor="black")

        self.Nome_1 = tk.Label(self.Frame_de_Busca)
        self.Nome_1.place(relx=0.014, rely=0.575, height=21, width=114
                , bordermode='ignore')
        self.Nome_1.configure(activebackground="#d9d9d9")
        self.Nome_1.configure(activeforeground="black")
        self.Nome_1.configure(anchor='w')
        self.Nome_1.configure(background="#efebe7")
        self.Nome_1.configure(compound='left')
        self.Nome_1.configure(disabledforeground="#b3b0ad")
        self.Nome_1.configure(font="-family {Segoe UI} -size 11")
        self.Nome_1.configure(foreground="black")
        self.Nome_1.configure(highlightbackground="#efebe7")
        self.Nome_1.configure(highlightcolor="black")
        self.Nome_1.configure(text='''Buscar Produto:''')

        self.Entry_Nome_1 = tk.Entry(self.Frame_de_Busca)
        self.Entry_Nome_1.place(relx=0.179, rely=0.575, height=20, relwidth=0.612
                , bordermode='ignore')
        self.Entry_Nome_1.configure(background="#ffffff")
        self.Entry_Nome_1.configure(disabledforeground="#b3b0ad")
        self.Entry_Nome_1.configure(exportselection="0")
        self.Entry_Nome_1.configure(font="TkFixedFont")
        self.Entry_Nome_1.configure(foreground="black")
        self.Entry_Nome_1.configure(highlightbackground="#efebe7")
        self.Entry_Nome_1.configure(highlightcolor="black")
        self.Entry_Nome_1.configure(insertbackground="black")
        self.Entry_Nome_1.configure(selectbackground="#d9d9d9")
        self.Entry_Nome_1.configure(selectforeground="black")

        self.btn_Pesquisar = tk.Button(self.Frame_de_Busca)
        self.btn_Pesquisar.place(relx=0.84, rely=0.575, height=26, width=97
                , bordermode='ignore')
        self.btn_Pesquisar.configure(activebackground="#d9d9d9")
        self.btn_Pesquisar.configure(activeforeground="black")
        self.btn_Pesquisar.configure(background="#efebe7")
        self.btn_Pesquisar.configure(command=sys_estoque_support.Pesquisar)
        self.btn_Pesquisar.configure(compound='left')
        self.btn_Pesquisar.configure(disabledforeground="#b3b0ad")
        self.btn_Pesquisar.configure(foreground="black")
        self.btn_Pesquisar.configure(highlightbackground="#efebe7")
        self.btn_Pesquisar.configure(highlightcolor="black")
        self.btn_Pesquisar.configure(text='''Buscar''')

        self.Assinatura_Dev = tk.Label(self.top)
        self.Assinatura_Dev.place(relx=0.013, rely=0.95, height=21, width=264)
        self.Assinatura_Dev.configure(activebackground="#d9d9d9")
        self.Assinatura_Dev.configure(activeforeground="black")
        self.Assinatura_Dev.configure(anchor='w')
        self.Assinatura_Dev.configure(background="#efebe7")
        self.Assinatura_Dev.configure(compound='left')
        self.Assinatura_Dev.configure(disabledforeground="#b3b0ad")
        self.Assinatura_Dev.configure(foreground="black")
        self.Assinatura_Dev.configure(highlightbackground="#efebe7")
        self.Assinatura_Dev.configure(highlightcolor="black")
        self.Assinatura_Dev.configure(text='''Desenvolvidor por Gabriel Levi - GL Systems''')

        self.Frame_da_Lista = tk.LabelFrame(self.top)
        self.Frame_da_Lista.place(relx=0.039, rely=0.233, relheight=0.39
                , relwidth=0.933)
        self.Frame_da_Lista.configure(relief='groove')
        self.Frame_da_Lista.configure(foreground="black")
        self.Frame_da_Lista.configure(text='''Listagem''')
        self.Frame_da_Lista.configure(background="#efebe7")
        self.Frame_da_Lista.configure(highlightbackground="#efebe7")
        self.Frame_da_Lista.configure(highlightcolor="black")

        self.btn_Remover = tk.Button(self.Frame_da_Lista)
        self.btn_Remover.place(relx=0.826, rely=0.746, height=26, width=107
                , bordermode='ignore')
        self.btn_Remover.configure(activebackground="#d9d9d9")
        self.btn_Remover.configure(activeforeground="#ffffff")
        self.btn_Remover.configure(background="#e8042c")
        self.btn_Remover.configure(compound='left')
        self.btn_Remover.configure(disabledforeground="#b3b0ad")
        self.btn_Remover.configure(foreground="black")
        self.btn_Remover.configure(highlightbackground="#efebe7")
        self.btn_Remover.configure(highlightcolor="black")
        self.btn_Remover.configure(text='''Remover''')

        self.btn_atualizar = tk.Button(self.Frame_da_Lista)
        self.btn_atualizar.place(relx=0.826, rely=0.498, height=26, width=107
                , bordermode='ignore')
        self.btn_atualizar.configure(activebackground="#d9d9d9")
        self.btn_atualizar.configure(activeforeground="black")
        self.btn_atualizar.configure(background="#e1e100")
        self.btn_atualizar.configure(command=sys_estoque_support.Atualizar)
        self.btn_atualizar.configure(compound='left')
        self.btn_atualizar.configure(disabledforeground="#b3b0ad")
        self.btn_atualizar.configure(foreground="black")
        self.btn_atualizar.configure(highlightbackground="#efebe7")
        self.btn_atualizar.configure(highlightcolor="black")
        self.btn_atualizar.configure(text='''Atualizar''')

        self.btn_Adicionar = tk.Button(self.Frame_da_Lista)
        self.btn_Adicionar.place(relx=0.826, rely=0.249, height=26, width=107
                , bordermode='ignore')
        self.btn_Adicionar.configure(activebackground="#d9d9d9")
        self.btn_Adicionar.configure(activeforeground="black")
        self.btn_Adicionar.configure(background="#80ff80")
        self.btn_Adicionar.configure(command=sys_estoque_support.Adicionar)
        self.btn_Adicionar.configure(compound='left')
        self.btn_Adicionar.configure(disabledforeground="#b3b0ad")
        self.btn_Adicionar.configure(foreground="black")
        self.btn_Adicionar.configure(highlightbackground="#efebe7")
        self.btn_Adicionar.configure(highlightcolor="black")
        self.btn_Adicionar.configure(text='''Adicionar''')

        _style_code()
        self.Frame_Lista = ScrolledTreeView(self.Frame_da_Lista)
        self.Frame_Lista.place(relx=0.012, rely=0.09, relheight=0.841
                , relwidth=0.788, bordermode='ignore')
        self.Frame_Lista.configure(columns="Col1 Col2 Col3")
        self.Frame_Lista.configure(show="headings")
        # build_treeview_support starting.
        self.Frame_Lista.heading("#0",text="ID")
        self.Frame_Lista.heading("#0",anchor="center")
        self.Frame_Lista.column("#0",width="80")
        self.Frame_Lista.column("#0",minwidth="20")
        self.Frame_Lista.column("#0",stretch="1")
        self.Frame_Lista.column("#0",anchor="w")
        self.Frame_Lista.heading("Col1",text="Nome")
        self.Frame_Lista.heading("Col1",anchor="center")
        self.Frame_Lista.column("Col1",width="300")
        self.Frame_Lista.column("Col1",minwidth="20")
        self.Frame_Lista.column("Col1",stretch="1")
        self.Frame_Lista.column("Col1",anchor="w")
        self.Frame_Lista.heading("Col2",text="Qtd")
        self.Frame_Lista.heading("Col2",anchor="center")
        self.Frame_Lista.column("Col2",width="161")
        self.Frame_Lista.column("Col2",minwidth="20")
        self.Frame_Lista.column("Col2",stretch="1")
        self.Frame_Lista.column("Col2",anchor="w")
        self.Frame_Lista.heading("Col3",text="Preço R$")
        self.Frame_Lista.heading("Col3",anchor="center")
        self.Frame_Lista.column("Col3",width="90")
        self.Frame_Lista.column("Col3",minwidth="20")
        self.Frame_Lista.column("Col3",stretch="1")
        self.Frame_Lista.column("Col3",anchor="w")

        self.Frame_de_Entrada = tk.LabelFrame(self.top)
        self.Frame_de_Entrada.place(relx=0.039, rely=0.058, relheight=0.167
                , relwidth=0.933)
        self.Frame_de_Entrada.configure(relief='groove')
        self.Frame_de_Entrada.configure(foreground="black")
        self.Frame_de_Entrada.configure(text='''Entrada de Produtos''')
        self.Frame_de_Entrada.configure(background="#efebe7")
        self.Frame_de_Entrada.configure(highlightbackground="#efebe7")
        self.Frame_de_Entrada.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame_de_Entrada)
        self.Label1.place(relx=0.551, rely=0.57, height=21, width=34
                , bordermode='ignore')
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#efebe7")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#b3b0ad")
        self.Label1.configure(font="-family {Segoe UI} -size 11")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="#efebe7")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''R$:''')

        self.Nome = tk.Label(self.Frame_de_Entrada)
        self.Nome.place(relx=0.014, rely=0.57, height=21, width=54
                , bordermode='ignore')
        self.Nome.configure(activebackground="#d9d9d9")
        self.Nome.configure(activeforeground="black")
        self.Nome.configure(anchor='w')
        self.Nome.configure(background="#efebe7")
        self.Nome.configure(compound='left')
        self.Nome.configure(disabledforeground="#b3b0ad")
        self.Nome.configure(font="-family {Segoe UI} -size 11")
        self.Nome.configure(foreground="black")
        self.Nome.configure(highlightbackground="#efebe7")
        self.Nome.configure(highlightcolor="black")
        self.Nome.configure(text='''Nome:''')

        self.Entry_Valor = tk.Entry(self.Frame_de_Entrada)
        self.Entry_Valor.place(relx=0.592, rely=0.57, height=20, relwidth=0.116
                , bordermode='ignore')
        self.Entry_Valor.configure(background="#ffffff")
        self.Entry_Valor.configure(disabledforeground="#b3b0ad")
        self.Entry_Valor.configure(exportselection="0")
        self.Entry_Valor.configure(font="-family {Courier New} -size 10")
        self.Entry_Valor.configure(foreground="black")
        self.Entry_Valor.configure(highlightbackground="#efebe7")
        self.Entry_Valor.configure(highlightcolor="black")
        self.Entry_Valor.configure(insertbackground="black")
        self.Entry_Valor.configure(selectbackground="#d9d9d9")
        self.Entry_Valor.configure(selectforeground="black")

        self.Entry_Qtd = tk.Entry(self.Frame_de_Entrada)
        self.Entry_Qtd.place(relx=0.386, rely=0.57, height=20, relwidth=0.116
                , bordermode='ignore')
        self.Entry_Qtd.configure(background="#ffffff")
        self.Entry_Qtd.configure(disabledforeground="#b3b0ad")
        self.Entry_Qtd.configure(exportselection="0")
        self.Entry_Qtd.configure(font="TkFixedFont")
        self.Entry_Qtd.configure(foreground="black")
        self.Entry_Qtd.configure(highlightbackground="#efebe7")
        self.Entry_Qtd.configure(highlightcolor="black")
        self.Entry_Qtd.configure(insertbackground="black")
        self.Entry_Qtd.configure(selectbackground="#d9d9d9")
        self.Entry_Qtd.configure(selectforeground="black")

        self.Qtd = tk.Label(self.Frame_de_Entrada)
        self.Qtd.place(relx=0.331, rely=0.57, height=21, width=34
                , bordermode='ignore')
        self.Qtd.configure(activebackground="#d9d9d9")
        self.Qtd.configure(activeforeground="black")
        self.Qtd.configure(anchor='w')
        self.Qtd.configure(background="#efebe7")
        self.Qtd.configure(compound='left')
        self.Qtd.configure(disabledforeground="#b3b0ad")
        self.Qtd.configure(font="-family {Segoe UI} -size 11")
        self.Qtd.configure(foreground="black")
        self.Qtd.configure(highlightbackground="#efebe7")
        self.Qtd.configure(highlightcolor="black")
        self.Qtd.configure(text='''Qtd:''')

        self.Entry_Nome = tk.Entry(self.Frame_de_Entrada)
        self.Entry_Nome.place(relx=0.096, rely=0.57, height=20, relwidth=0.198
                , bordermode='ignore')
        self.Entry_Nome.configure(background="#ffffff")
        self.Entry_Nome.configure(disabledforeground="#b3b0ad")
        self.Entry_Nome.configure(exportselection="0")
        self.Entry_Nome.configure(font="TkFixedFont")
        self.Entry_Nome.configure(foreground="black")
        self.Entry_Nome.configure(highlightbackground="#efebe7")
        self.Entry_Nome.configure(highlightcolor="black")
        self.Entry_Nome.configure(insertbackground="black")
        self.Entry_Nome.configure(selectbackground="#d9d9d9")
        self.Entry_Nome.configure(selectforeground="black")

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    sys_estoque_support.main()

if __name__ == '__main__':
    sys_estoque_support.main()




